In [83]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report

In [84]:
df =pd.read_csv("insurance.csv")
df

    Age   BMI  Children Smoker Region Exercise_Level  Insurance_Cost
0    50  34.0         0    Yes   West         Medium           19173
1    53  18.7         0    Yes   West           High           17365
2    64  30.0         4     No   West         Medium           24893
3    37  33.7         0    Yes  North           High           19040
4    36  21.1         0    Yes   East         Medium           13092
5    52  27.7         0     No   East            Low           20488
6    60  33.6         3    Yes   West         Medium           24476
7    34  18.6         3    Yes  North           High           15333
8    62  29.9         2    Yes  North           High           23165
9    60  23.1         1    Yes   East         Medium           20941
10   51  33.7         4     No  North            Low           23985
11   26  34.5         4     No  North            Low           16538
12   43  34.1         4     No  North         Medium           18850
13   19  26.1         2    Yes  South         Medium           12980
14   26  32.7         3    Yes   West           High           15378
15   26  32.4         2     No   East            Low           14003
16   57  23.4         4    Yes   East         Medium           22265
17   34  32.1         1    Yes  South            Low           16612
18   18  18.6         0    Yes   West         Medium            9156
19   42  28.1         3    Yes   East         Medium           19854
20   60  21.9         3     No  North            Low           19480
21   57  20.0         2     No   East         Medium           17930
22   59  19.3         3     No  North         Medium           20418
23   42  29.8         4    Yes  South           High           17909
24   56  23.8         4     No  North         Medium           22303
25   52  30.3         2     No   East         Medium           19423
26   20  19.1         4    Yes   East         Medium           13328
27   54  23.4         1    Yes   East           High           19553
28   61  27.2         2     No  South            Low           21340
29   61  31.4         1     No  South           High           23354
30   47  23.4         0     No   West           High           16275
31   55  28.6         1     No   East            Low           21136
32   51  33.1         0    Yes  North           High           18922
33   29  28.5         0     No  South            Low           13141
34   36  22.0         1     No   East           High           15895
35   54  18.4         2    Yes   East            Low           17129
36   61  32.8         4     No  South         Medium           23334
37   34  18.4         4    Yes   West           High           14859
38   27  32.9         0    Yes  South           High           15525
39   64  27.0         0    Yes  South           High           22510
40   29  34.0         2     No  North           High           16607
41   33  31.6         3     No  North         Medium           16663
42   41  35.0         1    Yes   West           High           19677
43   36  24.0         0     No   East         Medium           13384
44   25  31.0         4     No  South         Medium           15980
45   48  24.8         2    Yes   West         Medium           19716
46   38  26.2         1    Yes  North         Medium           17340
47   34  28.7         2     No  South            Low           14929
48   40  32.9         1    Yes   East            Low           16960
49   54  34.7         1     No  North           High           20760
50   33  31.1         0     No  North            Low           15639
51   23  25.1         2     No  North            Low           14763
52   25  25.2         2     No   West           High           13595
53   42  30.5         4    Yes   East           High           19796
54   35  22.1         4    Yes  South           High           16064
55   42  19.9         0    Yes   West            Low           12718
56   29  24.0         0    Yes   West            Low           11959
57   32  22.9         3     No   West           High           14733
58   43  23.0         4     No  North         Medium           16192
59   58  22.0         1    Yes   East           High           18259

In [85]:
df=df.drop("Smoker",axis=1)
df=df.drop("Region",axis=1)
df=df.drop("Exercise_Level",axis=1)

In [86]:
df.ndim

2

In [87]:
df.size

240

In [88]:
df.describe()

             Age        BMI   Children  Insurance_Cost
count  60.000000  60.000000  60.000000       60.000000
mean   42.833333  27.101667   1.916667    17784.750000
std    13.360918   5.307669   1.510322     3505.246777
min    18.000000  18.400000   0.000000     9156.000000
25%    33.000000  22.975000   0.750000    15366.750000
50%    42.000000  27.450000   2.000000    17352.500000
75%    54.250000  32.175000   3.000000    19995.000000
max    64.000000  35.000000   4.000000    24893.000000

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             60 non-null     int64
 1   BMI             60 non-null     float64
 2   Children        60 non-null     int64
 3   Insurance_Cost  60 non-null     int64
dtypes: float64(1), int64(3)
memory usage: 2.0 KB

In [90]:
print("Checking for Missing Values")
print(df.isnull().sum())

Checking for Missing Values
Age               0
BMI               0
Children          0
Insurance_Cost    0
dtype: int64

In [91]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [92]:
X = df.drop("Insurance_Cost", axis=1)   
y = df["Insurance_Cost"]

In [93]:
mm = MinMaxScaler()
scaled_features = mm.fit_transform(X)

In [94]:
scaled_data = pd.DataFrame(scaled_features, columns=X.columns)
print("MinMax Scaled Data :")
print(scaled_data)

MinMax Scaled Data :
         Age       BMI  Children
0   0.695652  0.939759      0.00
1   0.760870  0.018072      0.00
2   1.000000  0.698795      1.00
3   0.413043  0.921687      0.00
4   0.391304  0.162651      0.00
5   0.739130  0.560241      0.00
6   0.913043  0.915663      0.75
7   0.347826  0.012048      0.75
8   0.956522  0.692771      0.50
9   0.913043  0.283133      0.25
10  0.717391  0.921687      1.00
11  0.173913  0.969880      1.00
12  0.543478  0.945783      1.00
13  0.021739  0.463855      0.50
14  0.173913  0.861446      0.75
15  0.173913  0.843373      0.50
16  0.847826  0.301205      1.00
17  0.347826  0.825301      0.25
18  0.000000  0.012048      0.00
19  0.521739  0.584337      0.75
20  0.913043  0.210843      0.75
21  0.847826  0.096386      0.50
22  0.891304  0.054217      0.75
23  0.521739  0.686747      1.00
24  0.826087  0.325301      1.00
25  0.739130  0.716867      0.50
26  0.043478  0.042169      1.00
27  0.782609  0.301205      0.25
28  0.934783  0.530120      0.50
29  0.934783  0.783133      0.25
30  0.630435  0.301205      0.00
31  0.804348  0.614458      0.25
32  0.717391  0.885542      0.00
33  0.239130  0.608434      0.00
34  0.391304  0.216867      0.25
35  0.782609  0.000000      0.50
36  0.934783  0.867470      1.00
37  0.347826  0.000000      1.00
38  0.195652  0.873494      0.00
39  1.000000  0.518072      0.00
40  0.239130  0.939759      0.50
41  0.326087  0.795181      0.75
42  0.500000  1.000000      0.25
43  0.391304  0.337349      0.00
44  0.152174  0.759036      1.00
45  0.652174  0.385542      0.50
46  0.434783  0.469880      0.25
47  0.347826  0.620482      0.50
48  0.478261  0.873494      0.25
49  0.782609  0.981928      0.25
50  0.326087  0.765060      0.00
51  0.108696  0.403614      0.50
52  0.152174  0.409639      0.50
53  0.521739  0.728916      1.00
54  0.369565  0.222892      1.00
55  0.521739  0.090361      0.00
56  0.239130  0.337349      0.00
57  0.304348  0.271084      0.75
58  0.543478  0.277108      1.00
59  0.869565  0.216867      0.25

In [95]:
ss=StandardScaler()
scaled_features = ss.fit_transform(X)
scaled_data = pd.DataFrame(scaled_features, columns=X.columns)
print("Standard scaled Data :")
print(scaled_data)

Standard scaled Data :
         Age       BMI  Children
0   0.540917  1.310660 -1.279754
1   0.767347 -1.596288 -1.279754
2   1.597592  0.550673  1.391037
3  -0.440281  1.253661 -1.279754
4  -0.515758 -1.140296 -1.279754
5   0.691870  0.113681 -1.279754
6   1.295685  1.234661  0.723339
7  -0.666712 -1.615288  0.723339
8   1.446638  0.531674  0.055641
9   1.295685 -0.760303 -0.612056
10  0.616394  1.253661  1.391037
11 -1.270526  1.405658  1.391037
12  0.012579  1.329659  1.391037
13 -1.798863 -0.190313  0.055641
14 -1.270526  1.063664  0.723339
15 -1.270526  1.006665  0.055641
16  1.069254 -0.703304  1.391037
17 -0.666712  0.949666 -0.612056
18 -1.874340 -1.615288 -1.279754
19 -0.062897  0.189680  0.723339
20  1.295685 -0.988299  0.723339
21  1.069254 -1.349292  0.055641
22  1.220208 -1.482290  0.723339
23 -0.062897  0.512674  1.391037
24  0.993778 -0.627305  1.391037
25  0.691870  0.607672  0.055641
26 -1.723386 -1.520289  1.391037
27  0.842824 -0.703304 -0.612056
28  1.371161  0.018683  0.055641
29  1.371161  0.816669 -0.612056
30  0.314487 -0.703304 -1.279754
31  0.918301  0.284678 -0.612056
32  0.616394  1.139663 -1.279754
33 -1.044095  0.265679 -1.279754
34 -0.515758 -0.969299 -0.612056
35  0.842824 -1.653287  0.055641
36  1.371161  1.082664  1.391037
37 -0.666712 -1.653287  1.391037
38 -1.195049  1.101663 -1.279754
39  1.597592 -0.019316 -1.279754
40 -1.044095  1.310660  0.055641
41 -0.742188  0.854668  0.723339
42 -0.138374  1.500656 -0.612056
43 -0.515758 -0.589306 -1.279754
44 -1.346002  0.740670  1.391037
45  0.389963 -0.437309  0.055641
46 -0.364804 -0.171314 -0.612056
47 -0.666712  0.303678  0.055641
48 -0.213851  1.101663 -0.612056
49  0.842824  1.443657 -0.612056
50 -0.742188  0.759670 -1.279754
51 -1.496956 -0.380310  0.055641
52 -1.346002 -0.361310  0.055641
53 -0.062897  0.645672  1.391037
54 -0.591235 -0.950300  1.391037
55 -0.062897 -1.368292 -1.279754
56 -1.044095 -0.589306 -1.279754
57 -0.817665 -0.798302  0.723339
58  0.012579 -0.779303  1.391037
59  1.144731 -0.969299 -0.612056

In [96]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.feature_selection import SelectKBest, f_regression

In [97]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [98]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [99]:
y_pred = model.predict(X_test)
print("R2 Score:", r2_score(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

R2 Score: 0.8508769097395432
RMSE: 1143.4722550540223

In [100]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

In [101]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)

In [102]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [103]:
y_pred = knn.predict(X_test)
y_test

0     19173
5     20488
36    23334
45    19716
13    12980
54    16064
33    13141
48    16960
12    18850
57    14733
46    17340
50    15639
Name: Insurance_Cost, dtype: int64

In [104]:
print(confusion_matrix(y_test, y_pred))

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]]

In [105]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

        9156       0.00      0.00      0.00       0.0
       11959       0.00      0.00      0.00       0.0
       12980       0.00      0.00      0.00       1.0
       13092       0.00      0.00      0.00       0.0
       13141       0.00      0.00      0.00       1.0
       14733       0.00      0.00      0.00       1.0
       14929       0.00      0.00      0.00       0.0
       15639       0.00      0.00      0.00       1.0
       16064       0.00      0.00      0.00       1.0
       16192       0.00      0.00      0.00       0.0
       16275       0.00      0.00      0.00       0.0
       16960       0.00      0.00      0.00       1.0
       17340       0.00      0.00      0.00       1.0
       17909       0.00      0.00      0.00       0.0
       18850       0.00      0.00      0.00       1.0
       18922       0.00      0.00      0.00       0.0
       19173       0.00      0.00      0.00       1.0
       19716       0.00      0.00      0.00       1.0
       20488       0.00      0.00      0.00       1.0
       21340       0.00      0.00      0.00       0.0
       23334       0.00      0.00      0.00       1.0

    accuracy                           0.00      12.0
   macro avg       0.00      0.00      0.00      12.0
weighted avg       0.00      0.00      0.00      12.0